name: seq2seq

train_data_path: data/youtube_dataset/lmdb_train
val_data_path: data/youtube_dataset/lmdb_val
test_data_path: data/youtube_dataset/lmdb_test

wordembed_dim: 300
wordembed_path: data/fasttext/cc.ko.300.bin  # from fasttext

model_save_path: output/train_seq2seq
random_seed: -1

# model params
model: seq2seq
mean_dir_vec: [0.02638458673845107, -0.9996429354980532, -0.0042255285440260665, -0.05515719653732151, -0.998477242305561, -0.0009382259991350181, -0.05515719653732151, -0.998477242305561, -0.0009382259991350181, -0.9998449420671681, 0.00526838346577679, -0.016802855660830836, -0.22902108494722262, 0.9734208296178352, -0.0011095565431657925, 0.9526732849792824, 0.30394367621050383, 0.005643915168351122, 0.9997473113728224, 0.00042023293770663254, 0.022475248765942698, 0.16808688825858356, 0.9857617079287365, 0.00454457665429367, -0.9643145928309926, 0.2647450081558383, -0.002728866021263983]
mean_pose: [-0.01521560423345251, 0.5764794208104393, 0.002436800342578793, 0.0, 0.0, 0.0, -0.007986182708176807, -0.14456901705678968, -0.0001358452699020705, -0.015972365416353614, -0.28913803411357936, -0.000271690539804141, -0.24671332220948072, 0.001299981960030731, -0.004146131233228229, -0.333958613543517, 0.3721234102491703, -0.004568815388629877, -0.22680140907489543, 0.4063111587377214, -0.00393398476911512, 0.24830521194410135, 0.00010437240238221092, 0.005582131949582869, 0.313711722228135, 0.38368713697863677, 0.007350532226101516, 0.16962893217516073, 0.4232439369184838, 0.006942799487275916]
hidden_size: 200
n_layers: 2
dropout_prob: 0.1
z_type: none

# train params
epochs: 100
batch_size: 128
learning_rate: 0.0001
loss_regression_weight: 250
loss_kld_weight: 0.1  # weight for continuous motion term
loss_reg_weight: 25  # weight for motion variance term

# eval params
eval_net_path: output/train_h36m_gesture_autoencoder/gesture_autoencoder_checkpoint_best.bin

# dataset params
motion_resampling_framerate: 15
n_poses: 34
n_pre_poses: 4
subdivision_stride: 10
loader_workers: 0
